services:
  automart-streamlit:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
    command: streamlit run app/dashboard.py --server.port=8501 --server.address=0.0.0.0

  automart-django:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
